### ISSUE TITLE
Model loading | CUDA error | float16 | error in inference. 

### ISSUE THREAD

**Issue by HuaqingHe** [AlphacatPlus/VmambaIR#13]
```
While copying the parameter named **"decoder_level1.3.attn.Ac_logs",** whose dimensions in the model are torch.Size([2, 16]) and whose dimensions in the checkpoint are torch.Size([2, 16]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',). 
While copying the parameter named **"decoder_level1.3.attn.Dsc"**, whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.',).
```
I follow this blog to solve the loading question.
[https://stackoverflow.com/questions/77729360/problem-loading-model-state-dictionary-of-model-checkpoint](https://stackoverflow.com/questions/77729360/problem-loading-model-state-dictionary-of-model-checkpoint)
Add `.contiguous()` in [709](https://github.com/AlphacatPlus/VmambaIR/blob/51c2efbdcb50c6800b18fd4901b93f84b2a2af25/RealSR/VmambaIR/archs/MambaRealSR11_arch.py#L709) and [721](https://github.com/AlphacatPlus/VmambaIR/blob/51c2efbdcb50c6800b18fd4901b93f84b2a2af25/RealSR/VmambaIR/archs/MambaRealSR11_arch.py#L721) in arch file.

**Comment by HuaqingHe** [comment]
Additionally, while attempting to accelerate with CUDA and float16, I encountered different issues.

Due to the aforementioned contiguous issue causing Ac_logs and Dsc to fail to automatically align to the device, errors like device mismatch occurred when these parameters were used in cross_selective_scanC. By explicitly adding .cuda() to the code at [line 515](https://github.com/AlphacatPlus/VmambaIR/blob/51c2efbdcb50c6800b18fd4901b93f84b2a2af25/RealSR/VmambaIR/archs/MambaRealSR11_arch.py#L515) and [line 518](https://github.com/AlphacatPlus/VmambaIR/blob/51c2efbdcb50c6800b18fd4901b93f84b2a2af25/RealSR/VmambaIR/archs/MambaRealSR11_arch.py#L518), the problem was resolved.

After addressing the above, using float16 resulted in NaN values. Investigation revealed that mixed-precision calculations (float16 and float32) in the [SelectiveScanFn](https://github.com/AlphacatPlus/VmambaIR/blob/51c2efbdcb50c6800b18fd4901b93f84b2a2af25/RealSR/VmambaIR/archs/MambaRealSR11_arch.py#L67) caused invalid (inv) intermediate values, which later became NaN after normalization. The issue was fixed by updating the code to:

```
# Original:
# out, x, *rest = selective_scan_cuda.fwd(u, delta, A, B, C, D, delta_bias, delta_softplus, nrows)

# Updated:
out, x, *rest = selective_scan_cuda.fwd(
    u.float(), delta.float(), A.float(), B.float(), C.float(), 
    D.float(), delta_bias.float(), delta_softplus, nrows
)
```
